# Dependencies

# Permalinks
permalink:        /archive/:year/:month/:title/

# Setup
title:            Benjamin Hysell
description:      'My musings about software engineering, project management, and app development.'
url:              http://benhysell.github.io
baseurl:          /

author:           Benjamin Hysell
author_email:     ben.hysell@gmail.com
  name:           'Benjamin Hysell Software, Projects, and People'
  url:            https://twitter.com/benhysell

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
