# Dependencies
highlighter:      pygments

# Permalinks
permalink:        /archive/:year/:month/:title/

# Setup
title:            Benjamin Hysell
email:            ben.hysell@gmail.com
description:      'Software, Projects, and People'
url:              http://benhysell.github.io
baseurl:          /

author:
  name:           'Benjamin Hysell'
  url:            https://twitter.com/benhysell

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
